/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BreatheRouteImport } from './routes/breathe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreeningIndexRouteImport } from './routes/screening.index'
import { Route as ScreeningSettingsRouteImport } from './routes/screening.settings'
import { Route as ScreeningResourcesRouteImport } from './routes/screening.resources'
import { Route as ScreeningLibraryRouteImport } from './routes/screening.library'
import { Route as ScreeningHistoryRouteImport } from './routes/screening.history'
import { Route as JournalVoiceRouteImport } from './routes/journal.voice'
import { Route as JournalMemoriesRouteImport } from './routes/journal.memories'
import { Route as JournalIdRouteImport } from './routes/journal.$id'
import { Route as GratitudeWallRouteImport } from './routes/gratitude.wall'
import { Route as GratitudeTreeRouteImport } from './routes/gratitude.tree'
import { Route as GratitudeHistoryRouteImport } from './routes/gratitude.history'
import { Route as GratitudeForestRouteImport } from './routes/gratitude.forest'
import { Route as BreatheStatsRouteImport } from './routes/breathe.stats'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ScreeningTestIdRouteImport } from './routes/screening.test.$id'
import { Route as ScreeningResultsIdRouteImport } from './routes/screening.results.$id'
import { Route as ScreeningProcessingIdRouteImport } from './routes/screening.processing.$id'
import { Route as ScreeningInstructionsIdRouteImport } from './routes/screening.instructions.$id'
import { Route as ScreeningConsentIdRouteImport } from './routes/screening.consent.$id'
import { Route as ScreeningAssessmentIdRouteImport } from './routes/screening.assessment.$id'

const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BreatheRoute = BreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningIndexRoute = ScreeningIndexRouteImport.update({
  id: '/screening/',
  path: '/screening/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningSettingsRoute = ScreeningSettingsRouteImport.update({
  id: '/screening/settings',
  path: '/screening/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningResourcesRoute = ScreeningResourcesRouteImport.update({
  id: '/screening/resources',
  path: '/screening/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningLibraryRoute = ScreeningLibraryRouteImport.update({
  id: '/screening/library',
  path: '/screening/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningHistoryRoute = ScreeningHistoryRouteImport.update({
  id: '/screening/history',
  path: '/screening/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalVoiceRoute = JournalVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => JournalRoute,
} as any)
const JournalMemoriesRoute = JournalMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => JournalRoute,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JournalRoute,
} as any)
const GratitudeWallRoute = GratitudeWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => GratitudeRoute,
} as any)
const GratitudeTreeRoute = GratitudeTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => GratitudeRoute,
} as any)
const GratitudeHistoryRoute = GratitudeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => GratitudeRoute,
} as any)
const GratitudeForestRoute = GratitudeForestRouteImport.update({
  id: '/forest',
  path: '/forest',
  getParentRoute: () => GratitudeRoute,
} as any)
const BreatheStatsRoute = BreatheStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => BreatheRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningTestIdRoute = ScreeningTestIdRouteImport.update({
  id: '/screening/test/$id',
  path: '/screening/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningResultsIdRoute = ScreeningResultsIdRouteImport.update({
  id: '/screening/results/$id',
  path: '/screening/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningProcessingIdRoute = ScreeningProcessingIdRouteImport.update({
  id: '/screening/processing/$id',
  path: '/screening/processing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningInstructionsIdRoute = ScreeningInstructionsIdRouteImport.update({
  id: '/screening/instructions/$id',
  path: '/screening/instructions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningConsentIdRoute = ScreeningConsentIdRouteImport.update({
  id: '/screening/consent/$id',
  path: '/screening/consent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningAssessmentIdRoute = ScreeningAssessmentIdRouteImport.update({
  id: '/screening/assessment/$id',
  path: '/screening/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRouteWithChildren
  '/community': typeof CommunityRoute
  '/focus': typeof FocusRoute
  '/gratitude': typeof GratitudeRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/breathe/stats': typeof BreatheStatsRoute
  '/gratitude/forest': typeof GratitudeForestRoute
  '/gratitude/history': typeof GratitudeHistoryRoute
  '/gratitude/tree': typeof GratitudeTreeRoute
  '/gratitude/wall': typeof GratitudeWallRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/memories': typeof JournalMemoriesRoute
  '/journal/voice': typeof JournalVoiceRoute
  '/screening/history': typeof ScreeningHistoryRoute
  '/screening/library': typeof ScreeningLibraryRoute
  '/screening/resources': typeof ScreeningResourcesRoute
  '/screening/settings': typeof ScreeningSettingsRoute
  '/screening/': typeof ScreeningIndexRoute
  '/screening/assessment/$id': typeof ScreeningAssessmentIdRoute
  '/screening/consent/$id': typeof ScreeningConsentIdRoute
  '/screening/instructions/$id': typeof ScreeningInstructionsIdRoute
  '/screening/processing/$id': typeof ScreeningProcessingIdRoute
  '/screening/results/$id': typeof ScreeningResultsIdRoute
  '/screening/test/$id': typeof ScreeningTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRouteWithChildren
  '/community': typeof CommunityRoute
  '/focus': typeof FocusRoute
  '/gratitude': typeof GratitudeRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/breathe/stats': typeof BreatheStatsRoute
  '/gratitude/forest': typeof GratitudeForestRoute
  '/gratitude/history': typeof GratitudeHistoryRoute
  '/gratitude/tree': typeof GratitudeTreeRoute
  '/gratitude/wall': typeof GratitudeWallRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/memories': typeof JournalMemoriesRoute
  '/journal/voice': typeof JournalVoiceRoute
  '/screening/history': typeof ScreeningHistoryRoute
  '/screening/library': typeof ScreeningLibraryRoute
  '/screening/resources': typeof ScreeningResourcesRoute
  '/screening/settings': typeof ScreeningSettingsRoute
  '/screening': typeof ScreeningIndexRoute
  '/screening/assessment/$id': typeof ScreeningAssessmentIdRoute
  '/screening/consent/$id': typeof ScreeningConsentIdRoute
  '/screening/instructions/$id': typeof ScreeningInstructionsIdRoute
  '/screening/processing/$id': typeof ScreeningProcessingIdRoute
  '/screening/results/$id': typeof ScreeningResultsIdRoute
  '/screening/test/$id': typeof ScreeningTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breathe': typeof BreatheRouteWithChildren
  '/community': typeof CommunityRoute
  '/focus': typeof FocusRoute
  '/gratitude': typeof GratitudeRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/breathe/stats': typeof BreatheStatsRoute
  '/gratitude/forest': typeof GratitudeForestRoute
  '/gratitude/history': typeof GratitudeHistoryRoute
  '/gratitude/tree': typeof GratitudeTreeRoute
  '/gratitude/wall': typeof GratitudeWallRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/memories': typeof JournalMemoriesRoute
  '/journal/voice': typeof JournalVoiceRoute
  '/screening/history': typeof ScreeningHistoryRoute
  '/screening/library': typeof ScreeningLibraryRoute
  '/screening/resources': typeof ScreeningResourcesRoute
  '/screening/settings': typeof ScreeningSettingsRoute
  '/screening/': typeof ScreeningIndexRoute
  '/screening/assessment/$id': typeof ScreeningAssessmentIdRoute
  '/screening/consent/$id': typeof ScreeningConsentIdRoute
  '/screening/instructions/$id': typeof ScreeningInstructionsIdRoute
  '/screening/processing/$id': typeof ScreeningProcessingIdRoute
  '/screening/results/$id': typeof ScreeningResultsIdRoute
  '/screening/test/$id': typeof ScreeningTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breathe'
    | '/community'
    | '/focus'
    | '/gratitude'
    | '/journal'
    | '/api/chat'
    | '/breathe/stats'
    | '/gratitude/forest'
    | '/gratitude/history'
    | '/gratitude/tree'
    | '/gratitude/wall'
    | '/journal/$id'
    | '/journal/memories'
    | '/journal/voice'
    | '/screening/history'
    | '/screening/library'
    | '/screening/resources'
    | '/screening/settings'
    | '/screening/'
    | '/screening/assessment/$id'
    | '/screening/consent/$id'
    | '/screening/instructions/$id'
    | '/screening/processing/$id'
    | '/screening/results/$id'
    | '/screening/test/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breathe'
    | '/community'
    | '/focus'
    | '/gratitude'
    | '/journal'
    | '/api/chat'
    | '/breathe/stats'
    | '/gratitude/forest'
    | '/gratitude/history'
    | '/gratitude/tree'
    | '/gratitude/wall'
    | '/journal/$id'
    | '/journal/memories'
    | '/journal/voice'
    | '/screening/history'
    | '/screening/library'
    | '/screening/resources'
    | '/screening/settings'
    | '/screening'
    | '/screening/assessment/$id'
    | '/screening/consent/$id'
    | '/screening/instructions/$id'
    | '/screening/processing/$id'
    | '/screening/results/$id'
    | '/screening/test/$id'
  id:
    | '__root__'
    | '/'
    | '/breathe'
    | '/community'
    | '/focus'
    | '/gratitude'
    | '/journal'
    | '/api/chat'
    | '/breathe/stats'
    | '/gratitude/forest'
    | '/gratitude/history'
    | '/gratitude/tree'
    | '/gratitude/wall'
    | '/journal/$id'
    | '/journal/memories'
    | '/journal/voice'
    | '/screening/history'
    | '/screening/library'
    | '/screening/resources'
    | '/screening/settings'
    | '/screening/'
    | '/screening/assessment/$id'
    | '/screening/consent/$id'
    | '/screening/instructions/$id'
    | '/screening/processing/$id'
    | '/screening/results/$id'
    | '/screening/test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreatheRoute: typeof BreatheRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  FocusRoute: typeof FocusRoute
  GratitudeRoute: typeof GratitudeRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ScreeningHistoryRoute: typeof ScreeningHistoryRoute
  ScreeningLibraryRoute: typeof ScreeningLibraryRoute
  ScreeningResourcesRoute: typeof ScreeningResourcesRoute
  ScreeningSettingsRoute: typeof ScreeningSettingsRoute
  ScreeningIndexRoute: typeof ScreeningIndexRoute
  ScreeningAssessmentIdRoute: typeof ScreeningAssessmentIdRoute
  ScreeningConsentIdRoute: typeof ScreeningConsentIdRoute
  ScreeningInstructionsIdRoute: typeof ScreeningInstructionsIdRoute
  ScreeningProcessingIdRoute: typeof ScreeningProcessingIdRoute
  ScreeningResultsIdRoute: typeof ScreeningResultsIdRoute
  ScreeningTestIdRoute: typeof ScreeningTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathe': {
      id: '/breathe'
      path: '/breathe'
      fullPath: '/breathe'
      preLoaderRoute: typeof BreatheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/': {
      id: '/screening/'
      path: '/screening'
      fullPath: '/screening/'
      preLoaderRoute: typeof ScreeningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/settings': {
      id: '/screening/settings'
      path: '/screening/settings'
      fullPath: '/screening/settings'
      preLoaderRoute: typeof ScreeningSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/resources': {
      id: '/screening/resources'
      path: '/screening/resources'
      fullPath: '/screening/resources'
      preLoaderRoute: typeof ScreeningResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/library': {
      id: '/screening/library'
      path: '/screening/library'
      fullPath: '/screening/library'
      preLoaderRoute: typeof ScreeningLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/history': {
      id: '/screening/history'
      path: '/screening/history'
      fullPath: '/screening/history'
      preLoaderRoute: typeof ScreeningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/voice': {
      id: '/journal/voice'
      path: '/voice'
      fullPath: '/journal/voice'
      preLoaderRoute: typeof JournalVoiceRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/memories': {
      id: '/journal/memories'
      path: '/memories'
      fullPath: '/journal/memories'
      preLoaderRoute: typeof JournalMemoriesRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/gratitude/wall': {
      id: '/gratitude/wall'
      path: '/wall'
      fullPath: '/gratitude/wall'
      preLoaderRoute: typeof GratitudeWallRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/gratitude/tree': {
      id: '/gratitude/tree'
      path: '/tree'
      fullPath: '/gratitude/tree'
      preLoaderRoute: typeof GratitudeTreeRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/gratitude/history': {
      id: '/gratitude/history'
      path: '/history'
      fullPath: '/gratitude/history'
      preLoaderRoute: typeof GratitudeHistoryRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/gratitude/forest': {
      id: '/gratitude/forest'
      path: '/forest'
      fullPath: '/gratitude/forest'
      preLoaderRoute: typeof GratitudeForestRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/breathe/stats': {
      id: '/breathe/stats'
      path: '/stats'
      fullPath: '/breathe/stats'
      preLoaderRoute: typeof BreatheStatsRouteImport
      parentRoute: typeof BreatheRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/test/$id': {
      id: '/screening/test/$id'
      path: '/screening/test/$id'
      fullPath: '/screening/test/$id'
      preLoaderRoute: typeof ScreeningTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/results/$id': {
      id: '/screening/results/$id'
      path: '/screening/results/$id'
      fullPath: '/screening/results/$id'
      preLoaderRoute: typeof ScreeningResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/processing/$id': {
      id: '/screening/processing/$id'
      path: '/screening/processing/$id'
      fullPath: '/screening/processing/$id'
      preLoaderRoute: typeof ScreeningProcessingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/instructions/$id': {
      id: '/screening/instructions/$id'
      path: '/screening/instructions/$id'
      fullPath: '/screening/instructions/$id'
      preLoaderRoute: typeof ScreeningInstructionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/consent/$id': {
      id: '/screening/consent/$id'
      path: '/screening/consent/$id'
      fullPath: '/screening/consent/$id'
      preLoaderRoute: typeof ScreeningConsentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/assessment/$id': {
      id: '/screening/assessment/$id'
      path: '/screening/assessment/$id'
      fullPath: '/screening/assessment/$id'
      preLoaderRoute: typeof ScreeningAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BreatheRouteChildren {
  BreatheStatsRoute: typeof BreatheStatsRoute
}

const BreatheRouteChildren: BreatheRouteChildren = {
  BreatheStatsRoute: BreatheStatsRoute,
}

const BreatheRouteWithChildren =
  BreatheRoute._addFileChildren(BreatheRouteChildren)

interface GratitudeRouteChildren {
  GratitudeForestRoute: typeof GratitudeForestRoute
  GratitudeHistoryRoute: typeof GratitudeHistoryRoute
  GratitudeTreeRoute: typeof GratitudeTreeRoute
  GratitudeWallRoute: typeof GratitudeWallRoute
}

const GratitudeRouteChildren: GratitudeRouteChildren = {
  GratitudeForestRoute: GratitudeForestRoute,
  GratitudeHistoryRoute: GratitudeHistoryRoute,
  GratitudeTreeRoute: GratitudeTreeRoute,
  GratitudeWallRoute: GratitudeWallRoute,
}

const GratitudeRouteWithChildren = GratitudeRoute._addFileChildren(
  GratitudeRouteChildren,
)

interface JournalRouteChildren {
  JournalIdRoute: typeof JournalIdRoute
  JournalMemoriesRoute: typeof JournalMemoriesRoute
  JournalVoiceRoute: typeof JournalVoiceRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalIdRoute: JournalIdRoute,
  JournalMemoriesRoute: JournalMemoriesRoute,
  JournalVoiceRoute: JournalVoiceRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreatheRoute: BreatheRouteWithChildren,
  CommunityRoute: CommunityRoute,
  FocusRoute: FocusRoute,
  GratitudeRoute: GratitudeRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ScreeningHistoryRoute: ScreeningHistoryRoute,
  ScreeningLibraryRoute: ScreeningLibraryRoute,
  ScreeningResourcesRoute: ScreeningResourcesRoute,
  ScreeningSettingsRoute: ScreeningSettingsRoute,
  ScreeningIndexRoute: ScreeningIndexRoute,
  ScreeningAssessmentIdRoute: ScreeningAssessmentIdRoute,
  ScreeningConsentIdRoute: ScreeningConsentIdRoute,
  ScreeningInstructionsIdRoute: ScreeningInstructionsIdRoute,
  ScreeningProcessingIdRoute: ScreeningProcessingIdRoute,
  ScreeningResultsIdRoute: ScreeningResultsIdRoute,
  ScreeningTestIdRoute: ScreeningTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
