/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TreatmentPlansRouteImport } from './routes/treatment-plans'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfilePublicRouteImport } from './routes/profile-public'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CpdRouteImport } from './routes/cpd'
import { Route as CaseConferencesRouteImport } from './routes/case-conferences'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as SettingsTelehealthRouteImport } from './routes/settings.telehealth'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsSupportRouteImport } from './routes/settings.support'
import { Route as SettingsServicesRouteImport } from './routes/settings.services'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsPracticeRouteImport } from './routes/settings.practice'
import { Route as SettingsPayoutsRouteImport } from './routes/settings.payouts'
import { Route as SettingsPaymentsRouteImport } from './routes/settings.payments'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsLogoutRouteImport } from './routes/settings.logout'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsEmergencyProtocolRouteImport } from './routes/settings.emergency-protocol'
import { Route as SettingsDeleteRouteImport } from './routes/settings.delete'
import { Route as SettingsDataRouteImport } from './routes/settings.data'
import { Route as SettingsDangerRouteImport } from './routes/settings.danger'
import { Route as SettingsCredentialsRouteImport } from './routes/settings.credentials'
import { Route as SettingsComplianceRouteImport } from './routes/settings.compliance'
import { Route as SettingsClinicalDefaultsRouteImport } from './routes/settings.clinical-defaults'
import { Route as SettingsAvailabilityRouteImport } from './routes/settings.availability'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccessibilityRouteImport } from './routes/settings.accessibility'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsPidRouteImport } from './routes/patients.$pid'
import { Route as ComplianceExportRouteImport } from './routes/compliance.export'
import { Route as ComplianceConsentRouteImport } from './routes/compliance.consent'
import { Route as ComplianceAuditRouteImport } from './routes/compliance.audit'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as PatientsPidIndexRouteImport } from './routes/patients.$pid.index'
import { Route as PatientsPidTimelineRouteImport } from './routes/patients.$pid.timeline'
import { Route as PatientsPidNotesRouteImport } from './routes/patients.$pid.notes'
import { Route as PatientsPidDocumentsRouteImport } from './routes/patients.$pid.documents'
import { Route as PatientsPidChartRouteImport } from './routes/patients.$pid.chart'
import { Route as PatientsPidNotesIndexRouteImport } from './routes/patients.$pid.notes.index'
import { Route as PatientsPidNotesNewRouteImport } from './routes/patients.$pid.notes.new'
import { Route as PatientsPidNotesNidRouteImport } from './routes/patients.$pid.notes.$nid'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentPlansRoute = TreatmentPlansRouteImport.update({
  id: '/treatment-plans',
  path: '/treatment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePublicRoute = ProfilePublicRouteImport.update({
  id: '/profile-public',
  path: '/profile-public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRoute = CpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseConferencesRoute = CaseConferencesRouteImport.update({
  id: '/case-conferences',
  path: '/case-conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const SettingsTelehealthRoute = SettingsTelehealthRouteImport.update({
  id: '/telehealth',
  path: '/telehealth',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSupportRoute = SettingsSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServicesRoute = SettingsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPracticeRoute = SettingsPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPayoutsRoute = SettingsPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogoutRoute = SettingsLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmergencyProtocolRoute =
  SettingsEmergencyProtocolRouteImport.update({
    id: '/emergency-protocol',
    path: '/emergency-protocol',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsDeleteRoute = SettingsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDangerRoute = SettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCredentialsRoute = SettingsCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsComplianceRoute = SettingsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsClinicalDefaultsRoute =
  SettingsClinicalDefaultsRouteImport.update({
    id: '/clinical-defaults',
    path: '/clinical-defaults',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsAvailabilityRoute = SettingsAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPidRoute = PatientsPidRouteImport.update({
  id: '/$pid',
  path: '/$pid',
  getParentRoute: () => PatientsRoute,
} as any)
const ComplianceExportRoute = ComplianceExportRouteImport.update({
  id: '/compliance/export',
  path: '/compliance/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceConsentRoute = ComplianceConsentRouteImport.update({
  id: '/compliance/consent',
  path: '/compliance/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceAuditRoute = ComplianceAuditRouteImport.update({
  id: '/compliance/audit',
  path: '/compliance/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PatientsPidIndexRoute = PatientsPidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPidRoute,
} as any)
const PatientsPidTimelineRoute = PatientsPidTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PatientsPidRoute,
} as any)
const PatientsPidNotesRoute = PatientsPidNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => PatientsPidRoute,
} as any)
const PatientsPidDocumentsRoute = PatientsPidDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientsPidRoute,
} as any)
const PatientsPidChartRoute = PatientsPidChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => PatientsPidRoute,
} as any)
const PatientsPidNotesIndexRoute = PatientsPidNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPidNotesRoute,
} as any)
const PatientsPidNotesNewRoute = PatientsPidNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsPidNotesRoute,
} as any)
const PatientsPidNotesNidRoute = PatientsPidNotesNidRouteImport.update({
  id: '/$nid',
  path: '/$nid',
  getParentRoute: () => PatientsPidNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/auth': typeof AuthRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/case-conferences': typeof CaseConferencesRoute
  '/cpd': typeof CpdRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/groups': typeof GroupsRoute
  '/homework': typeof HomeworkRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payouts': typeof PayoutsRoute
  '/peers': typeof PeersRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile-public': typeof ProfilePublicRoute
  '/referrals': typeof ReferralsRoute
  '/research': typeof ResearchRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/supervision': typeof SupervisionRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/consent': typeof ComplianceConsentRoute
  '/compliance/export': typeof ComplianceExportRoute
  '/patients/$pid': typeof PatientsPidRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/clinical-defaults': typeof SettingsClinicalDefaultsRoute
  '/settings/compliance': typeof SettingsComplianceRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/emergency-protocol': typeof SettingsEmergencyProtocolRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/logout': typeof SettingsLogoutRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/payouts': typeof SettingsPayoutsRoute
  '/settings/practice': typeof SettingsPracticeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/support': typeof SettingsSupportRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/telehealth': typeof SettingsTelehealthRoute
  '/auth/': typeof AuthIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/patients/$pid/chart': typeof PatientsPidChartRoute
  '/patients/$pid/documents': typeof PatientsPidDocumentsRoute
  '/patients/$pid/notes': typeof PatientsPidNotesRouteWithChildren
  '/patients/$pid/timeline': typeof PatientsPidTimelineRoute
  '/patients/$pid/': typeof PatientsPidIndexRoute
  '/patients/$pid/notes/$nid': typeof PatientsPidNotesNidRoute
  '/patients/$pid/notes/new': typeof PatientsPidNotesNewRoute
  '/patients/$pid/notes/': typeof PatientsPidNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/availability': typeof AvailabilityRoute
  '/case-conferences': typeof CaseConferencesRoute
  '/cpd': typeof CpdRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/groups': typeof GroupsRoute
  '/homework': typeof HomeworkRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/payouts': typeof PayoutsRoute
  '/peers': typeof PeersRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile-public': typeof ProfilePublicRoute
  '/referrals': typeof ReferralsRoute
  '/research': typeof ResearchRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sessions': typeof SessionsRoute
  '/supervision': typeof SupervisionRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/consent': typeof ComplianceConsentRoute
  '/compliance/export': typeof ComplianceExportRoute
  '/patients/new': typeof PatientsNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/clinical-defaults': typeof SettingsClinicalDefaultsRoute
  '/settings/compliance': typeof SettingsComplianceRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/emergency-protocol': typeof SettingsEmergencyProtocolRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/logout': typeof SettingsLogoutRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/payouts': typeof SettingsPayoutsRoute
  '/settings/practice': typeof SettingsPracticeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/support': typeof SettingsSupportRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/telehealth': typeof SettingsTelehealthRoute
  '/auth': typeof AuthIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/patients/$pid/chart': typeof PatientsPidChartRoute
  '/patients/$pid/documents': typeof PatientsPidDocumentsRoute
  '/patients/$pid/timeline': typeof PatientsPidTimelineRoute
  '/patients/$pid': typeof PatientsPidIndexRoute
  '/patients/$pid/notes/$nid': typeof PatientsPidNotesNidRoute
  '/patients/$pid/notes/new': typeof PatientsPidNotesNewRoute
  '/patients/$pid/notes': typeof PatientsPidNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRoute
  '/auth': typeof AuthRouteWithChildren
  '/availability': typeof AvailabilityRoute
  '/case-conferences': typeof CaseConferencesRoute
  '/cpd': typeof CpdRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/groups': typeof GroupsRoute
  '/homework': typeof HomeworkRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payouts': typeof PayoutsRoute
  '/peers': typeof PeersRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile-public': typeof ProfilePublicRoute
  '/referrals': typeof ReferralsRoute
  '/research': typeof ResearchRoute
  '/reviews': typeof ReviewsRoute
  '/risk': typeof RiskRoute
  '/schedule': typeof ScheduleRoute
  '/services': typeof ServicesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/supervision': typeof SupervisionRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/treatment-plans': typeof TreatmentPlansRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/compliance/audit': typeof ComplianceAuditRoute
  '/compliance/consent': typeof ComplianceConsentRoute
  '/compliance/export': typeof ComplianceExportRoute
  '/patients/$pid': typeof PatientsPidRouteWithChildren
  '/patients/new': typeof PatientsNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/availability': typeof SettingsAvailabilityRoute
  '/settings/clinical-defaults': typeof SettingsClinicalDefaultsRoute
  '/settings/compliance': typeof SettingsComplianceRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/delete': typeof SettingsDeleteRoute
  '/settings/emergency-protocol': typeof SettingsEmergencyProtocolRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/logout': typeof SettingsLogoutRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/payouts': typeof SettingsPayoutsRoute
  '/settings/practice': typeof SettingsPracticeRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/support': typeof SettingsSupportRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/telehealth': typeof SettingsTelehealthRoute
  '/auth/': typeof AuthIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/patients/$pid/chart': typeof PatientsPidChartRoute
  '/patients/$pid/documents': typeof PatientsPidDocumentsRoute
  '/patients/$pid/notes': typeof PatientsPidNotesRouteWithChildren
  '/patients/$pid/timeline': typeof PatientsPidTimelineRoute
  '/patients/$pid/': typeof PatientsPidIndexRoute
  '/patients/$pid/notes/$nid': typeof PatientsPidNotesNidRoute
  '/patients/$pid/notes/new': typeof PatientsPidNotesNewRoute
  '/patients/$pid/notes/': typeof PatientsPidNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assessments'
    | '/auth'
    | '/availability'
    | '/case-conferences'
    | '/cpd'
    | '/dashboard'
    | '/documents'
    | '/groups'
    | '/homework'
    | '/inbox'
    | '/library'
    | '/notes'
    | '/notifications'
    | '/patients'
    | '/payments'
    | '/payouts'
    | '/peers'
    | '/prescriptions'
    | '/profile-public'
    | '/referrals'
    | '/research'
    | '/reviews'
    | '/risk'
    | '/schedule'
    | '/services'
    | '/sessions'
    | '/settings'
    | '/supervision'
    | '/support'
    | '/templates'
    | '/treatment-plans'
    | '/waitlist'
    | '/auth/login'
    | '/auth/signup'
    | '/compliance/audit'
    | '/compliance/consent'
    | '/compliance/export'
    | '/patients/$pid'
    | '/patients/new'
    | '/settings/about'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/clinical-defaults'
    | '/settings/compliance'
    | '/settings/credentials'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/delete'
    | '/settings/emergency-protocol'
    | '/settings/integrations'
    | '/settings/logout'
    | '/settings/notifications'
    | '/settings/payments'
    | '/settings/payouts'
    | '/settings/practice'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/services'
    | '/settings/support'
    | '/settings/team'
    | '/settings/telehealth'
    | '/auth/'
    | '/patients/'
    | '/settings/'
    | '/patients/$pid/chart'
    | '/patients/$pid/documents'
    | '/patients/$pid/notes'
    | '/patients/$pid/timeline'
    | '/patients/$pid/'
    | '/patients/$pid/notes/$nid'
    | '/patients/$pid/notes/new'
    | '/patients/$pid/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assessments'
    | '/availability'
    | '/case-conferences'
    | '/cpd'
    | '/dashboard'
    | '/documents'
    | '/groups'
    | '/homework'
    | '/inbox'
    | '/library'
    | '/notes'
    | '/notifications'
    | '/payments'
    | '/payouts'
    | '/peers'
    | '/prescriptions'
    | '/profile-public'
    | '/referrals'
    | '/research'
    | '/reviews'
    | '/risk'
    | '/schedule'
    | '/services'
    | '/sessions'
    | '/supervision'
    | '/support'
    | '/templates'
    | '/treatment-plans'
    | '/waitlist'
    | '/auth/login'
    | '/auth/signup'
    | '/compliance/audit'
    | '/compliance/consent'
    | '/compliance/export'
    | '/patients/new'
    | '/settings/about'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/clinical-defaults'
    | '/settings/compliance'
    | '/settings/credentials'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/delete'
    | '/settings/emergency-protocol'
    | '/settings/integrations'
    | '/settings/logout'
    | '/settings/notifications'
    | '/settings/payments'
    | '/settings/payouts'
    | '/settings/practice'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/services'
    | '/settings/support'
    | '/settings/team'
    | '/settings/telehealth'
    | '/auth'
    | '/patients'
    | '/settings'
    | '/patients/$pid/chart'
    | '/patients/$pid/documents'
    | '/patients/$pid/timeline'
    | '/patients/$pid'
    | '/patients/$pid/notes/$nid'
    | '/patients/$pid/notes/new'
    | '/patients/$pid/notes'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assessments'
    | '/auth'
    | '/availability'
    | '/case-conferences'
    | '/cpd'
    | '/dashboard'
    | '/documents'
    | '/groups'
    | '/homework'
    | '/inbox'
    | '/library'
    | '/notes'
    | '/notifications'
    | '/patients'
    | '/payments'
    | '/payouts'
    | '/peers'
    | '/prescriptions'
    | '/profile-public'
    | '/referrals'
    | '/research'
    | '/reviews'
    | '/risk'
    | '/schedule'
    | '/services'
    | '/sessions'
    | '/settings'
    | '/supervision'
    | '/support'
    | '/templates'
    | '/treatment-plans'
    | '/waitlist'
    | '/auth/login'
    | '/auth/signup'
    | '/compliance/audit'
    | '/compliance/consent'
    | '/compliance/export'
    | '/patients/$pid'
    | '/patients/new'
    | '/settings/about'
    | '/settings/accessibility'
    | '/settings/appearance'
    | '/settings/availability'
    | '/settings/clinical-defaults'
    | '/settings/compliance'
    | '/settings/credentials'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/delete'
    | '/settings/emergency-protocol'
    | '/settings/integrations'
    | '/settings/logout'
    | '/settings/notifications'
    | '/settings/payments'
    | '/settings/payouts'
    | '/settings/practice'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/services'
    | '/settings/support'
    | '/settings/team'
    | '/settings/telehealth'
    | '/auth/'
    | '/patients/'
    | '/settings/'
    | '/patients/$pid/chart'
    | '/patients/$pid/documents'
    | '/patients/$pid/notes'
    | '/patients/$pid/timeline'
    | '/patients/$pid/'
    | '/patients/$pid/notes/$nid'
    | '/patients/$pid/notes/new'
    | '/patients/$pid/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AuthRoute: typeof AuthRouteWithChildren
  AvailabilityRoute: typeof AvailabilityRoute
  CaseConferencesRoute: typeof CaseConferencesRoute
  CpdRoute: typeof CpdRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  GroupsRoute: typeof GroupsRoute
  HomeworkRoute: typeof HomeworkRoute
  InboxRoute: typeof InboxRoute
  LibraryRoute: typeof LibraryRoute
  NotesRoute: typeof NotesRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  PayoutsRoute: typeof PayoutsRoute
  PeersRoute: typeof PeersRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfilePublicRoute: typeof ProfilePublicRoute
  ReferralsRoute: typeof ReferralsRoute
  ResearchRoute: typeof ResearchRoute
  ReviewsRoute: typeof ReviewsRoute
  RiskRoute: typeof RiskRoute
  ScheduleRoute: typeof ScheduleRoute
  ServicesRoute: typeof ServicesRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupervisionRoute: typeof SupervisionRoute
  SupportRoute: typeof SupportRoute
  TemplatesRoute: typeof TemplatesRoute
  TreatmentPlansRoute: typeof TreatmentPlansRoute
  WaitlistRoute: typeof WaitlistRoute
  ComplianceAuditRoute: typeof ComplianceAuditRoute
  ComplianceConsentRoute: typeof ComplianceConsentRoute
  ComplianceExportRoute: typeof ComplianceExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment-plans': {
      id: '/treatment-plans'
      path: '/treatment-plans'
      fullPath: '/treatment-plans'
      preLoaderRoute: typeof TreatmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-public': {
      id: '/profile-public'
      path: '/profile-public'
      fullPath: '/profile-public'
      preLoaderRoute: typeof ProfilePublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd': {
      id: '/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof CpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-conferences': {
      id: '/case-conferences'
      path: '/case-conferences'
      fullPath: '/case-conferences'
      preLoaderRoute: typeof CaseConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/settings/telehealth': {
      id: '/settings/telehealth'
      path: '/telehealth'
      fullPath: '/settings/telehealth'
      preLoaderRoute: typeof SettingsTelehealthRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/support': {
      id: '/settings/support'
      path: '/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof SettingsSupportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/services': {
      id: '/settings/services'
      path: '/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof SettingsServicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/practice': {
      id: '/settings/practice'
      path: '/practice'
      fullPath: '/settings/practice'
      preLoaderRoute: typeof SettingsPracticeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payouts': {
      id: '/settings/payouts'
      path: '/payouts'
      fullPath: '/settings/payouts'
      preLoaderRoute: typeof SettingsPayoutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logout': {
      id: '/settings/logout'
      path: '/logout'
      fullPath: '/settings/logout'
      preLoaderRoute: typeof SettingsLogoutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/emergency-protocol': {
      id: '/settings/emergency-protocol'
      path: '/emergency-protocol'
      fullPath: '/settings/emergency-protocol'
      preLoaderRoute: typeof SettingsEmergencyProtocolRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/delete': {
      id: '/settings/delete'
      path: '/delete'
      fullPath: '/settings/delete'
      preLoaderRoute: typeof SettingsDeleteRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger': {
      id: '/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof SettingsDangerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/credentials': {
      id: '/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof SettingsCredentialsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/compliance': {
      id: '/settings/compliance'
      path: '/compliance'
      fullPath: '/settings/compliance'
      preLoaderRoute: typeof SettingsComplianceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/clinical-defaults': {
      id: '/settings/clinical-defaults'
      path: '/clinical-defaults'
      fullPath: '/settings/clinical-defaults'
      preLoaderRoute: typeof SettingsClinicalDefaultsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/availability': {
      id: '/settings/availability'
      path: '/availability'
      fullPath: '/settings/availability'
      preLoaderRoute: typeof SettingsAvailabilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/accessibility': {
      id: '/settings/accessibility'
      path: '/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof SettingsAccessibilityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$pid': {
      id: '/patients/$pid'
      path: '/$pid'
      fullPath: '/patients/$pid'
      preLoaderRoute: typeof PatientsPidRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/compliance/export': {
      id: '/compliance/export'
      path: '/compliance/export'
      fullPath: '/compliance/export'
      preLoaderRoute: typeof ComplianceExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/consent': {
      id: '/compliance/consent'
      path: '/compliance/consent'
      fullPath: '/compliance/consent'
      preLoaderRoute: typeof ComplianceConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/audit': {
      id: '/compliance/audit'
      path: '/compliance/audit'
      fullPath: '/compliance/audit'
      preLoaderRoute: typeof ComplianceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/patients/$pid/': {
      id: '/patients/$pid/'
      path: '/'
      fullPath: '/patients/$pid/'
      preLoaderRoute: typeof PatientsPidIndexRouteImport
      parentRoute: typeof PatientsPidRoute
    }
    '/patients/$pid/timeline': {
      id: '/patients/$pid/timeline'
      path: '/timeline'
      fullPath: '/patients/$pid/timeline'
      preLoaderRoute: typeof PatientsPidTimelineRouteImport
      parentRoute: typeof PatientsPidRoute
    }
    '/patients/$pid/notes': {
      id: '/patients/$pid/notes'
      path: '/notes'
      fullPath: '/patients/$pid/notes'
      preLoaderRoute: typeof PatientsPidNotesRouteImport
      parentRoute: typeof PatientsPidRoute
    }
    '/patients/$pid/documents': {
      id: '/patients/$pid/documents'
      path: '/documents'
      fullPath: '/patients/$pid/documents'
      preLoaderRoute: typeof PatientsPidDocumentsRouteImport
      parentRoute: typeof PatientsPidRoute
    }
    '/patients/$pid/chart': {
      id: '/patients/$pid/chart'
      path: '/chart'
      fullPath: '/patients/$pid/chart'
      preLoaderRoute: typeof PatientsPidChartRouteImport
      parentRoute: typeof PatientsPidRoute
    }
    '/patients/$pid/notes/': {
      id: '/patients/$pid/notes/'
      path: '/'
      fullPath: '/patients/$pid/notes/'
      preLoaderRoute: typeof PatientsPidNotesIndexRouteImport
      parentRoute: typeof PatientsPidNotesRoute
    }
    '/patients/$pid/notes/new': {
      id: '/patients/$pid/notes/new'
      path: '/new'
      fullPath: '/patients/$pid/notes/new'
      preLoaderRoute: typeof PatientsPidNotesNewRouteImport
      parentRoute: typeof PatientsPidNotesRoute
    }
    '/patients/$pid/notes/$nid': {
      id: '/patients/$pid/notes/$nid'
      path: '/$nid'
      fullPath: '/patients/$pid/notes/$nid'
      preLoaderRoute: typeof PatientsPidNotesNidRouteImport
      parentRoute: typeof PatientsPidNotesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PatientsPidNotesRouteChildren {
  PatientsPidNotesNidRoute: typeof PatientsPidNotesNidRoute
  PatientsPidNotesNewRoute: typeof PatientsPidNotesNewRoute
  PatientsPidNotesIndexRoute: typeof PatientsPidNotesIndexRoute
}

const PatientsPidNotesRouteChildren: PatientsPidNotesRouteChildren = {
  PatientsPidNotesNidRoute: PatientsPidNotesNidRoute,
  PatientsPidNotesNewRoute: PatientsPidNotesNewRoute,
  PatientsPidNotesIndexRoute: PatientsPidNotesIndexRoute,
}

const PatientsPidNotesRouteWithChildren =
  PatientsPidNotesRoute._addFileChildren(PatientsPidNotesRouteChildren)

interface PatientsPidRouteChildren {
  PatientsPidChartRoute: typeof PatientsPidChartRoute
  PatientsPidDocumentsRoute: typeof PatientsPidDocumentsRoute
  PatientsPidNotesRoute: typeof PatientsPidNotesRouteWithChildren
  PatientsPidTimelineRoute: typeof PatientsPidTimelineRoute
  PatientsPidIndexRoute: typeof PatientsPidIndexRoute
}

const PatientsPidRouteChildren: PatientsPidRouteChildren = {
  PatientsPidChartRoute: PatientsPidChartRoute,
  PatientsPidDocumentsRoute: PatientsPidDocumentsRoute,
  PatientsPidNotesRoute: PatientsPidNotesRouteWithChildren,
  PatientsPidTimelineRoute: PatientsPidTimelineRoute,
  PatientsPidIndexRoute: PatientsPidIndexRoute,
}

const PatientsPidRouteWithChildren = PatientsPidRoute._addFileChildren(
  PatientsPidRouteChildren,
)

interface PatientsRouteChildren {
  PatientsPidRoute: typeof PatientsPidRouteWithChildren
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPidRoute: PatientsPidRouteWithChildren,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAvailabilityRoute: typeof SettingsAvailabilityRoute
  SettingsClinicalDefaultsRoute: typeof SettingsClinicalDefaultsRoute
  SettingsComplianceRoute: typeof SettingsComplianceRoute
  SettingsCredentialsRoute: typeof SettingsCredentialsRoute
  SettingsDangerRoute: typeof SettingsDangerRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDeleteRoute: typeof SettingsDeleteRoute
  SettingsEmergencyProtocolRoute: typeof SettingsEmergencyProtocolRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsLogoutRoute: typeof SettingsLogoutRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsPayoutsRoute: typeof SettingsPayoutsRoute
  SettingsPracticeRoute: typeof SettingsPracticeRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsServicesRoute: typeof SettingsServicesRoute
  SettingsSupportRoute: typeof SettingsSupportRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsTelehealthRoute: typeof SettingsTelehealthRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAvailabilityRoute: SettingsAvailabilityRoute,
  SettingsClinicalDefaultsRoute: SettingsClinicalDefaultsRoute,
  SettingsComplianceRoute: SettingsComplianceRoute,
  SettingsCredentialsRoute: SettingsCredentialsRoute,
  SettingsDangerRoute: SettingsDangerRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDeleteRoute: SettingsDeleteRoute,
  SettingsEmergencyProtocolRoute: SettingsEmergencyProtocolRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsLogoutRoute: SettingsLogoutRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsPayoutsRoute: SettingsPayoutsRoute,
  SettingsPracticeRoute: SettingsPracticeRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsServicesRoute: SettingsServicesRoute,
  SettingsSupportRoute: SettingsSupportRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsTelehealthRoute: SettingsTelehealthRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentsRoute: AssessmentsRoute,
  AuthRoute: AuthRouteWithChildren,
  AvailabilityRoute: AvailabilityRoute,
  CaseConferencesRoute: CaseConferencesRoute,
  CpdRoute: CpdRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  GroupsRoute: GroupsRoute,
  HomeworkRoute: HomeworkRoute,
  InboxRoute: InboxRoute,
  LibraryRoute: LibraryRoute,
  NotesRoute: NotesRoute,
  NotificationsRoute: NotificationsRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  PayoutsRoute: PayoutsRoute,
  PeersRoute: PeersRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfilePublicRoute: ProfilePublicRoute,
  ReferralsRoute: ReferralsRoute,
  ResearchRoute: ResearchRoute,
  ReviewsRoute: ReviewsRoute,
  RiskRoute: RiskRoute,
  ScheduleRoute: ScheduleRoute,
  ServicesRoute: ServicesRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupervisionRoute: SupervisionRoute,
  SupportRoute: SupportRoute,
  TemplatesRoute: TemplatesRoute,
  TreatmentPlansRoute: TreatmentPlansRoute,
  WaitlistRoute: WaitlistRoute,
  ComplianceAuditRoute: ComplianceAuditRoute,
  ComplianceConsentRoute: ComplianceConsentRoute,
  ComplianceExportRoute: ComplianceExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
